name: flutter_firestore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
